# Generated by Django 4.1.4 on 2023-11-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="failedimport",
            unique_together={("data_id", "reason")},
        ),
    ]
