# Generated by Django 4.1.4 on 2023-11-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_failedimport_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="failedimport",
            name="data_type",
            field=models.TextField(),
        ),
    ]
