# Generated by Django 4.1.4 on 2023-11-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_failedimport_data_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="failedimport",
            name="airtable_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
