# Generated by Django 4.1.4 on 2023-08-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.SlugField(editable=False, primary_key=True, serialize=False),
                ),
                ("file", models.FileField(upload_to="files/")),
                ("name", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
