# Generated by Django 4.1.4 on 2023-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.FileField(upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.SlugField(
                editable=False, max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
