# Generated by Django 4.1.4 on 2023-10-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_uploadedfile_hash_alter_uploadedfile_file_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
