# The Chart.yaml contains metadata about the Chart.
# This is information is used when your run `helm list`.
# Version number will be v2 for now.
apiVersion: v2
# Name MUST match the name of the directory
name: inecuria
# A description is useful to know what it does
description: Inecuria Wiki
# Allows for us to go from a deployed Chart back to the source repository
sources:
  - https://github.com/WittgreffeR/inecuria
# version is used for versioning charts.
# However we do not push our charts to a chart repository so we do not worry about this value.
version: 1.0.0
# appversion corresponds to the version of the application deployed by this chart.
# We set this to the same value as the docker image, which is normally the git hash.
# This is set a deploy time. SO DO NOT TOUCH!
appVersion: REPLACE_IMAGE_TAG
