app:
  env:
    ENVIRONMENT: qa
  django:
    env:
      INTEGRATE_WITH_SENTRY: false
      AWS_STORAGE_BUCKET_NAME: inecuria-logos-qa

  ingress:
    hosts:
      - inecuria.com
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
