{{/*
Secrets allows you for storing arbitrary data in a secure manner inside the cluster.
They are stored in secure storage called etcd.
They are commonly used for storing config files and environment variables.
https://kubernetes.io/docs/concepts/configuration/secret/
*/}}
apiVersion: v1
kind: Secret
metadata:
  # Name is based of Release name
  name: {{ template "inecuria.fullname" . }}
  # Standard set of labels for consistency
  labels:
    {{- include "inecuria.commonLabels" . | nindent 4 }}
# Type is always Opaque
type: Opaque
data:
{{- range $key, $value := .Values.django.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "inecuria.fullname" . }}-db-migration-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inecuria.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
{{- range $key, $value := .Values.django.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "inecuria.fullname" . }}-import-data-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "inecuria.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: import-data
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-1"
type: Opaque
data:
{{- range $key, $value := .Values.django.envSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}