apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "inecuria.fullname" . }}-db-migration
  labels:
    {{- include "inecuria.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: db-migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "0"
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: {{ template "inecuria.fullname" . }}-db-migration
      labels:
        {{- include "inecuria.commonLabels" . | nindent 8 }}
        app.kubernetes.io/component: db-migration
    spec:
      restartPolicy: Never
      containers:
        - name: db-migration
          image: "{{ .Values.app.django.image.repository }}:{{ default .Values.app.django.image.tag .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args: [
            "-ec",
            "python manage.py migrate"
          ]
          envFrom:
            - secretRef:
                name: {{ template "inecuria.fullname" . }}-db-migration-secrets
          env:
            {{- range $key, $value := .Values.app.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
            {{- range $key, $value := .Values.app.django.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
